# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI/CD

on: [pull_request, push] 
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      URL_INFURA: ${{ secrets.URL_INFURA }}
      ACCOUNT_PRIVATE: ${{ secrets.ACCOUNT_PRIVATE }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install all dependencies
      run: npm i 
    - name: Launch the test on React app
      run: npm test
    - name: Launch hardhat tests on smart contract
      run: npx hardhat test
